# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://127.0.0.1:8000/api/buyers
Accept: application/json

###

POST http://127.0.0.1:8000/api/categories
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###

GET http://127.0.0.1:8000/api/users
Accept: application/json

###

GET http://127.0.0.1:8000/api/users/10
Accept: application/json

###

GET http://laravelapi-test.us-east-2.elasticbeanstalk.com/
Accept: application/json

###

POST http://laravelapi-test.us-east-2.elasticbeanstalk.com/api/categories
Content-Type: application/x-www-form-urlencoded

id=99&content=new-element

###

GET http://laravelapi-test.us-east-2.elasticbeanstalk.com/api/products
Accept: application/json

###

POST http://127.0.0.1:8000/api/users
Content-Type: application/x-www-form-urlencoded

name=Jose

###

PUT http://127.0.0.1:8000/api/users/10
Content-Type: application/x-www-form-urlencoded

email=tkoelpin@example.com&name=Della Cormier


###

DELETE http://127.0.0.1:8000/api/users/3

###

GET http://127.0.0.1:8000/api/users/95
Accept: application/json

###

GET http://127.0.0.1:8000/api/buyers
Accept: application/json

###

GET http://127.0.0.1:8000/api/buyers/132131321
Accept: application/json

###

GET http://127.0.0.1:8000/api/sellers/14
Accept: application/json

###

GET http://127.0.0.1:8000/api/categories
Accept: application/json

###

POST http://127.0.0.1:8000/api/categories
Content-Type: application/x-www-form-urlencoded

name=Nueva Categoria&description=Descripcion de la nueva categoria

###

PUT http://127.0.0.1:8000/api/categories/32
Content-Type: application/x-www-form-urlencoded

name=Nueva Categoria ACTUALIZADA&description=Descripcion de la nueva categoria ACTUALIZADA

###

DELETE http://127.0.0.1:8000/api/categories/1
Content-Type: application/x-www-form-urlencoded

###

GET http://127.0.0.1:8000/api/products
Accept: application/json

###

GET http://127.0.0.1:8000/api/products/100
Accept: application/json

###

GET http://127.0.0.1:8000/api/transactions
Accept: application/json

###

GET http://127.0.0.1:8000/api/transactions/999
Accept: application/json

###

GET http://127.0.0.1:8000/api/transactions/999/categories
Accept: application/json

###

GET http://127.0.0.1:8000/api/transactions/999/sellers
Accept: application/json

###

GET http://127.0.0.1:8000/api/buyers/9/transactions
Accept: application/json

###

GET http://127.0.0.1:8000/api/buyers/9/products
Accept: application/json

###

GET http://127.0.0.1:8000/api/buyers/9/sellers
Accept: application/json

###

GET http://127.0.0.1:8000/api/buyers/9/categories
Accept: application/json

###

GET http://127.0.0.1:8000/api/categories/4/products
Accept: application/json

###

GET http://127.0.0.1:8000/api/categories/4/sellers
Accept: application/json

###

GET http://127.0.0.1:8000/api/categories/4/transactions
Accept: application/json

###

GET http://127.0.0.1:8000/api/categories/4/buyers
Accept: application/json

###